// <auto-generated />
using GroupChatApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GroupChatApp.Migrations
{
    [DbContext(typeof(GroupChatContext))]
    partial class GroupChatContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("GroupChatApp.Models.Group", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GroupName");

                    b.HasKey("ID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GroupChatApp.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddedBy");

                    b.Property<string>("ChatMessage");

                    b.Property<int>("GroupId");

                    b.HasKey("ID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("GroupChatApp.Models.UserGroup", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GroupId");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
